// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: items.sql

package repository

import (
	"context"
	"time"
)

const createItem = `-- name: CreateItem :one
INSERT INTO items (
    board_id, title, description
) VALUES (
    ?, ?, ?
)
RETURNING id, board_id, title, description, state_id, created_at, last_updated_at
`

type CreateItemParams struct {
	BoardID     int64  `json:"boardId"`
	Title       string `json:"title"`
	Description string `json:"description"`
}

func (q *Queries) CreateItem(ctx context.Context, arg CreateItemParams) (Item, error) {
	row := q.db.QueryRowContext(ctx, createItem, arg.BoardID, arg.Title, arg.Description)
	var i Item
	err := row.Scan(
		&i.ID,
		&i.BoardID,
		&i.Title,
		&i.Description,
		&i.StateID,
		&i.CreatedAt,
		&i.LastUpdatedAt,
	)
	return i, err
}

const createItemWithState = `-- name: CreateItemWithState :one
INSERT INTO items (
    board_id, title, description, state_id
) VALUES (
    ?, ?, ?, ?
)
RETURNING id, board_id, title, description, state_id, created_at, last_updated_at
`

type CreateItemWithStateParams struct {
	BoardID     int64  `json:"boardId"`
	Title       string `json:"title"`
	Description string `json:"description"`
	StateID     int64  `json:"stateId"`
}

func (q *Queries) CreateItemWithState(ctx context.Context, arg CreateItemWithStateParams) (Item, error) {
	row := q.db.QueryRowContext(ctx, createItemWithState,
		arg.BoardID,
		arg.Title,
		arg.Description,
		arg.StateID,
	)
	var i Item
	err := row.Scan(
		&i.ID,
		&i.BoardID,
		&i.Title,
		&i.Description,
		&i.StateID,
		&i.CreatedAt,
		&i.LastUpdatedAt,
	)
	return i, err
}

const deleteItem = `-- name: DeleteItem :exec
DELETE FROM items
WHERE id = ?
`

func (q *Queries) DeleteItem(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteItem, id)
	return err
}

const getItemByID = `-- name: GetItemByID :one
SELECT
    items.id,
    items.board_id,
    items.title,
    items.description,
    items.state_id,
    items.created_at,
    items.last_updated_at,
    json_extract(states, '$') AS "state"
FROM items
JOIN states ON items.state_id = states.id
WHERE items.id = ?
`

type GetItemByIDRow struct {
	ID            int64       `json:"id"`
	BoardID       int64       `json:"boardId"`
	Title         string      `json:"title"`
	Description   string      `json:"description"`
	StateID       int64       `json:"stateId"`
	CreatedAt     time.Time   `json:"createdAt"`
	LastUpdatedAt time.Time   `json:"lastUpdatedAt"`
	State         interface{} `json:"state"`
}

func (q *Queries) GetItemByID(ctx context.Context, id int64) (GetItemByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getItemByID, id)
	var i GetItemByIDRow
	err := row.Scan(
		&i.ID,
		&i.BoardID,
		&i.Title,
		&i.Description,
		&i.StateID,
		&i.CreatedAt,
		&i.LastUpdatedAt,
		&i.State,
	)
	return i, err
}

const listItemsByBoardID = `-- name: ListItemsByBoardID :many
SELECT
    items.id,
    items.board_id,
    items.title,
    items.description,
    items.state_id,
    items.created_at,
    items.last_updated_at,
    json_extract(states, '$') AS "state"
FROM items
JOIN states ON items.state_id = states.id
WHERE items.board_id = ?
ORDER BY items.created_at
`

type ListItemsByBoardIDRow struct {
	ID            int64       `json:"id"`
	BoardID       int64       `json:"boardId"`
	Title         string      `json:"title"`
	Description   string      `json:"description"`
	StateID       int64       `json:"stateId"`
	CreatedAt     time.Time   `json:"createdAt"`
	LastUpdatedAt time.Time   `json:"lastUpdatedAt"`
	State         interface{} `json:"state"`
}

func (q *Queries) ListItemsByBoardID(ctx context.Context, boardID int64) ([]ListItemsByBoardIDRow, error) {
	rows, err := q.db.QueryContext(ctx, listItemsByBoardID, boardID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListItemsByBoardIDRow
	for rows.Next() {
		var i ListItemsByBoardIDRow
		if err := rows.Scan(
			&i.ID,
			&i.BoardID,
			&i.Title,
			&i.Description,
			&i.StateID,
			&i.CreatedAt,
			&i.LastUpdatedAt,
			&i.State,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateItemByID = `-- name: UpdateItemByID :one
UPDATE items
SET
    title = COALESCE(?, title),
    description = COALESCE(?, description),
    state_id = COALESCE(?, state_id),
    last_updated_at = CURRENT_TIMESTAMP
WHERE id = ?
RETURNING id, board_id, title, description, state_id, created_at, last_updated_at
`

type UpdateItemByIDParams struct {
	Title       string `json:"title"`
	Description string `json:"description"`
	StateID     int64  `json:"stateId"`
	ID          int64  `json:"id"`
}

func (q *Queries) UpdateItemByID(ctx context.Context, arg UpdateItemByIDParams) (Item, error) {
	row := q.db.QueryRowContext(ctx, updateItemByID,
		arg.Title,
		arg.Description,
		arg.StateID,
		arg.ID,
	)
	var i Item
	err := row.Scan(
		&i.ID,
		&i.BoardID,
		&i.Title,
		&i.Description,
		&i.StateID,
		&i.CreatedAt,
		&i.LastUpdatedAt,
	)
	return i, err
}
