name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "*"

env:
  GOPATH: /go_path
  GOCACHE: /go_cache

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          check-latest: true

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          args: --timeout 5m

  build:
    name: build
    needs: lint
    strategy:
      matrix:
        os: [linux]
        arch: [amd64]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          check-latest: true
      - name: Build
        run: |
          if [ "${{ matrix.os }}" = "windows" ]; then
            go build -ldflags="-s -w -X main.Version=$(git rev-parse --short HEAD)" -o bin/donezo.exe
          else
            go build -ldflags="-s -w -X main.Version=$(git rev-parse --short HEAD)" -o bin/donezo
          fi
        env:
          CGO_ENABLED: 1
          GOOS: ${{ matrix.os }}
          GOARCH: ${{ matrix.arch }}
      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: donezo-${{ matrix.goos }}-${{ matrix.goarch }}
          path: bin/*
