name: Release
run-name: Build and release ${{ github.ref_name }}

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: write

jobs:
  env:
    runs-on: [ubuntu-latest]
    outputs:
      version: ${{ steps.env.outputs.version }}
    steps:
      - name: Set build version
        id: env
        run: |
          version="${{ github.ref_name }}"
          version="${version#v}"
          echo "version=$version" >> $GITHUB_OUTPUT

  ci:
    needs: env
    uses: ./.github/workflows/reusable-ci.yml
    with:
      version: ${{ needs.env.outputs.version }}

  release:
    needs: ci
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifacts
        id: download
        uses: actions/download-artifact@v4
        with:
          path: ${{ github.workspace }}/artifacts
      - name: Prepare release assets
        run: |
          mkdir dist
          find "${{ github.workspace }}/artifacts" -type f -name "donezo" | while read -r file; do
            parent_dir=$(basename "$(dirname "$file")")
            temp_dir=$(mktemp -d)
            cp "$file" "$temp_dir/donezo"
            chmod +x "$temp_dir/donezo"
            tar -czf "dist/${parent_dir}.tar.gz" -C "$temp_dir" donezo
            rm -rf "$temp_dir"
          done
        shell: bash
      - name: Create GitHub release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/*
          tag_name: ${{ github.ref_name }}
          generate_release_notes: true
          draft: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
